---
abstract: 'Perl::Critic policies inspired by #perl on freenode IRC'
author:
  - 'Dan Book <dbook@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.042, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Freenode
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Perl::Critic::Freenode:
    file: lib/Perl/Critic/Freenode.pm
    version: '0.013'
  Perl::Critic::Freenode::Utils:
    file: lib/Perl/Critic/Freenode/Utils.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::AmpersandSubCalls:
    file: lib/Perl/Critic/Policy/Freenode/AmpersandSubCalls.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::BarewordFilehandles:
    file: lib/Perl/Critic/Policy/Freenode/BarewordFilehandles.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::ConditionalDeclarations:
    file: lib/Perl/Critic/Policy/Freenode/ConditionalDeclarations.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::ConditionalImplicitReturn:
    file: lib/Perl/Critic/Policy/Freenode/ConditionalImplicitReturn.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::DeprecatedFeatures:
    file: lib/Perl/Critic/Policy/Freenode/DeprecatedFeatures.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::DiscouragedModules:
    file: lib/Perl/Critic/Policy/Freenode/DiscouragedModules.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::DollarAB:
    file: lib/Perl/Critic/Policy/Freenode/DollarAB.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::Each:
    file: lib/Perl/Critic/Policy/Freenode/Each.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::EmptyReturn:
    file: lib/Perl/Critic/Policy/Freenode/EmptyReturn.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::ModPerl:
    file: lib/Perl/Critic/Policy/Freenode/ModPerl.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::OpenArgs:
    file: lib/Perl/Critic/Policy/Freenode/OpenArgs.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::POSIXImports:
    file: lib/Perl/Critic/Policy/Freenode/POSIXImports.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::Prototypes:
    file: lib/Perl/Critic/Policy/Freenode/Prototypes.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::StrictWarnings:
    file: lib/Perl/Critic/Policy/Freenode/StrictWarnings.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::Threads:
    file: lib/Perl/Critic/Policy/Freenode/Threads.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::Wantarray:
    file: lib/Perl/Critic/Policy/Freenode/Wantarray.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::WarningsSwitch:
    file: lib/Perl/Critic/Policy/Freenode/WarningsSwitch.pm
    version: '0.013'
  Perl::Critic::Policy::Freenode::WhileDiamondDefaultAssignment:
    file: lib/Perl/Critic/Policy/Freenode/WhileDiamondDefaultAssignment.pm
    version: '0.013'
requires:
  Carp: '0'
  Exporter: '0'
  List::Util: '1.33'
  Perl::Critic: '1.126'
  Perl::Critic::Policy::Subroutines::ProhibitAmpersandSigils: '1.126'
  Perl::Critic::Policy::Variables::ProhibitConditionalDeclarations: '1.126'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.010001'
  version: '0'
resources:
  bugtracker: https://github.com/Grinnz/Perl-Critic-Freenode/issues
  homepage: https://github.com/Grinnz/Perl-Critic-Freenode
  repository: https://github.com/Grinnz/Perl-Critic-Freenode.git
version: '0.013'
x_contributors:
  - 'Dan Book <grinnz@gmail.com>'
  - 'Dan Book <grinnz@grinnz.com>'
  - 'Graham Knop <haarg@haarg.org>'
